/* ===========================================================
   Aetherbound — game data (heroes, enemies, skills, stages)
   Exposed on window.GAME_DATA
   Owner: Backend
   =========================================================== */
(function () {
  'use strict';

  const ELEMENTS = {
    fire:  { id: 'fire',  name: 'Fire',  color: '#ff6a4d', glyph: '♨' },
    water: { id: 'water', name: 'Water', color: '#5ab9ff', glyph: '≋' },
    wind:  { id: 'wind',  name: 'Wind',  color: '#7ee787', glyph: '✺' },
    light: { id: 'light', name: 'Light', color: '#ffd86a', glyph: '☼' },
    dark:  { id: 'dark',  name: 'Dark',  color: '#c084ff', glyph: '☾' },
  };
  const TIER_SCALE = { 3: 1.0, 4: 1.4, 5: 1.8 };

  function elementMod(att, def) {
    if (att === def) return 1.0;
    if ((att === 'fire'  && def === 'wind')  ||
        (att === 'wind'  && def === 'water') ||
        (att === 'water' && def === 'fire')) return 1.5;
    if ((att === 'wind'  && def === 'fire')  ||
        (att === 'water' && def === 'wind')  ||
        (att === 'fire'  && def === 'water')) return 0.75;
    if (att === 'light' && def === 'dark') return 1.5;
    if (att === 'dark'  && def === 'light') return 1.5;
    return 1.0;
  }

  const SKILLS = {
    // ===== Hero skills 3* =====
    burningSlash: { name: 'Burning Slash', type: 'attack', target: 'enemy', mul: 1.4, cd: 0,
      desc: 'A flaming strike. 1.4x ATK fire damage.', anim: 'lunge' },
    cinderWave:   { name: 'Cinder Wave',   type: 'aoe',    target: 'enemies', mul: 0.95, cd: 3,
      desc: 'Engulfs all enemies in cinders. 0.95x ATK to all.', anim: 'lunge' },
    waterBolt:    { name: 'Water Bolt',    type: 'attack', target: 'enemy', mul: 1.5, cd: 0,
      desc: 'A focused water bolt. 1.5x ATK.', anim: 'lunge' },
    tsunami:      { name: 'Tsunami',       type: 'aoe',    target: 'enemies', mul: 1.25, cd: 4,
      desc: 'Drowns all enemies. 1.25x ATK to all.', anim: 'lunge' },
    quickShot:    { name: 'Quick Shot',    type: 'multihit', target: 'enemy', mul: 0.85, hits: 2, cd: 0,
      desc: 'Fires two swift arrows. Hits twice for 0.85x ATK each.', anim: 'lunge' },
    hurricaneVolley: { name: 'Hurricane Volley', type: 'aoe', target: 'enemies', mul: 0.80, cd: 3,
      desc: 'Strikes all enemies with a wind volley. 30% chance to reduce SPD by 30% for 2 turns.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'spd', amount: -0.30, chance: 0.30, turns: 2, label: 'SPD-' } },
    smite:        { name: 'Smite',         type: 'attack', target: 'enemy', mul: 1.2, cd: 0,
      desc: 'Holy strike. 1.2x ATK light damage.', anim: 'lunge' },
    sanctifiedLight: { name: 'Sanctified Light', type: 'heal', target: 'allies', healPct: 0.32, cd: 3,
      desc: 'Restores 32% Max HP to all allies.', anim: 'glow' },
    shadowStrike: { name: 'Shadow Strike', type: 'attack', target: 'enemy', mul: 1.6, cd: 0, critBonus: 0.15,
      desc: '1.6x ATK with +15% crit rate.', anim: 'lunge' },
    veilOfNight:  { name: 'Veil of Night', type: 'attack', target: 'enemy', mul: 2.6, cd: 4,
      desc: '2.6x ATK strike. Reduces own DEF by 30% for 2 turns.', anim: 'lunge',
      onSelf: { kind: 'debuff', stat: 'def', amount: -0.30, turns: 2, label: 'DEF-' } },
    crushingBlow: { name: 'Crushing Blow', type: 'attack', target: 'enemy', mul: 1.3, cd: 2,
      desc: '1.3x ATK. 30% chance to stun for 1 turn.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'stun', chance: 0.30, turns: 1, label: 'STUN' } },
    aegis: { name: 'Aegis', type: 'buff', target: 'ally', cd: 4,
      desc: 'Grants an ally a shield equal to 25% of their Max HP for 2 turns.', anim: 'glow',
      onCast: { kind: 'shield', pct: 0.25, turns: 2, label: 'SHIELD' } },
    frostBash:    { name: 'Frost Bash',    type: 'attack', target: 'enemy', mul: 1.3, cd: 0,
      desc: '1.3x ATK water strike. 30% chance to stun for 1 turn.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'stun', chance: 0.30, turns: 1, label: 'STUN' } },
    bulwark:      { name: 'Bulwark', type: 'buff', target: 'self', cd: 4,
      desc: 'Self shield = 25% Max HP for 2 turns.', anim: 'glow',
      onCast: { kind: 'shield', pct: 0.25, turns: 2, label: 'SHIELD' } },
    swiftStrike:  { name: 'Swift Strike',  type: 'attack', target: 'enemy', mul: 1.4, cd: 0, critBonus: 0.10,
      desc: '1.4x ATK with +10% crit rate.', anim: 'lunge' },
    riposte:      { name: 'Riposte',       type: 'attack', target: 'enemy', mul: 1.6, cd: 3,
      desc: '1.6x ATK strike. Self SPD +20% for 2 turns.', anim: 'lunge',
      onSelf: { kind: 'buff', stat: 'spd', amount: 0.20, turns: 2, label: 'SPD+' } },
    // ===== Hero skills 4* =====
    flameWhip:    { name: 'Flame Whip',    type: 'attack', target: 'enemy', mul: 1.5, cd: 0,
      desc: "1.5x ATK. 60% chance to reduce the target's ATK by 25% for 2 turns.", anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'atk', amount: -0.25, turns: 2, chance: 0.60, label: 'ATK-' } },
    infernoCage:  { name: 'Inferno Cage',  type: 'aoe',    target: 'enemies', mul: 1.10, cd: 3,
      desc: '1.1x ATK to all. 70% chance to reduce DEF by 25% for 2 turns.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'def', amount: -0.25, turns: 2, chance: 0.70, label: 'DEF-' } },
    tideStrike:   { name: 'Tide Strike',   type: 'attack', target: 'enemy', mul: 1.6, cd: 0,
      desc: 'Crashing tide. 1.6x ATK.', anim: 'lunge' },
    whirlpoolGuard: { name: 'Whirlpool Guard', type: 'buff', target: 'self', cd: 4,
      desc: 'Self shield = 25% Max HP and ATK +25% for 2 turns.', anim: 'glow',
      onCast: { kind: 'shield', pct: 0.25, turns: 2, label: 'SHIELD' },
      onSelf: { kind: 'buff', stat: 'atk', amount: 0.25, turns: 2, label: 'ATK+' } },
    thunderLance: { name: 'Thunder Lance', type: 'attack', target: 'enemy', mul: 1.7, cd: 0, critBonus: 0.20,
      desc: '1.7x ATK with +20% crit rate.', anim: 'lunge' },
    galeRush:     { name: 'Gale Rush',     type: 'multihit', target: 'enemy', mul: 0.85, hits: 3, cd: 3,
      desc: 'Three swift lances. 0.85x ATK each.', anim: 'lunge' },
    judgmentLight:{ name: 'Judgment Light',type: 'attack', target: 'enemy', mul: 1.4, cd: 0,
      desc: '1.4x ATK light damage.', anim: 'lunge' },
    dawnsBlessing:{ name: "Dawn's Blessing", type: 'heal', target: 'allies', healPct: 0.34, cd: 4,
      desc: 'Restores 34% Max HP to all allies.', anim: 'glow' },
    eclipseStrike:{ name: 'Eclipse Strike',type: 'attack', target: 'enemy', mul: 1.8, cd: 0,
      desc: '1.8x ATK dark strike.', anim: 'lunge' },
    voidStep:     { name: 'Void Step',     type: 'buff', target: 'self', cd: 4,
      desc: 'Self ATK +30% and SPD +30% for 2 turns.', anim: 'glow',
      onCast: { kind: 'buff', stat: 'atk', amount: 0.30, turns: 2, label: 'ATK+' },
      onSelf: { kind: 'buff', stat: 'spd', amount: 0.30, turns: 2, label: 'SPD+' } },
    bonecrush:    { name: 'Bonecrush',     type: 'attack', target: 'enemy', mul: 1.3, cd: 2,
      desc: '1.3x ATK. 40% chance to stun for 1 turn.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'stun', chance: 0.40, turns: 1, label: 'STUN' } },
    reaperGuard:  { name: 'Reaper Guard',  type: 'buff', target: 'ally', cd: 4,
      desc: 'Grants an ally a shield = 30% Max HP for 2 turns. Self DEF +20% for 2 turns.', anim: 'glow',
      onCast: { kind: 'shield', pct: 0.30, turns: 2, label: 'SHIELD' },
      onSelf: { kind: 'buff', stat: 'def', amount: 0.20, turns: 2, label: 'DEF+' } },
    // ===== Hero skills 5* =====
    phoenixBlade: { name: 'Phoenix Blade', type: 'attack', target: 'enemy', mul: 1.9, cd: 0,
      desc: '1.9x ATK phoenix strike.', anim: 'lunge' },
    emberStorm:   { name: 'Ember Storm',   type: 'aoe',    target: 'enemies', mul: 1.4, cd: 4,
      desc: 'Storm of embers. 1.4x ATK to all.', anim: 'lunge' },
    starfire:     { name: 'Starfire',      type: 'attack', target: 'enemy', mul: 1.5, cd: 0,
      desc: '1.5x ATK light burst.', anim: 'lunge' },
    celestialBloom:{ name: 'Celestial Bloom', type: 'heal', target: 'allies', healPct: 0.38, cd: 4,
      desc: 'Restores 38% Max HP to all allies.', anim: 'glow' },
    galeStrike:   { name: 'Gale Strike',   type: 'attack', target: 'enemy', mul: 2.0, cd: 0, critBonus: 0.20,
      desc: '2.0x ATK with +20% crit. The wind cuts through all armor.', anim: 'lunge' },
    cycloneBreak: { name: 'Cyclone Break', type: 'aoe',    target: 'enemies', mul: 1.5, cd: 4,
      desc: '1.5x ATK to all enemies. 40% chance to reduce SPD by 25% for 2 turns.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'spd', amount: -0.25, chance: 0.40, turns: 2, label: 'SPD-' } },
    voidSlash:    { name: 'Void Slash',    type: 'attack', target: 'enemy', mul: 2.2, cd: 0, critBonus: 0.10,
      desc: '2.2x ATK dark strike with +10% crit rate.', anim: 'lunge' },
    abyssalEdge:  { name: 'Abyssal Edge',  type: 'attack', target: 'enemy', mul: 3.2, cd: 4,
      desc: '3.2x ATK strike. Reduces own DEF by 35% for 2 turns.', anim: 'lunge',
      onSelf: { kind: 'debuff', stat: 'def', amount: -0.35, turns: 2, label: 'DEF-' } },
    tidalSurge:   { name: 'Tidal Surge',   type: 'attack', target: 'enemy', mul: 1.8, cd: 0,
      desc: 'A powerful surging tide. 1.8x ATK water damage.', anim: 'lunge' },
    divineRestoration: { name: 'Divine Restoration', type: 'heal', target: 'allies', healPct: 0.42, cd: 4,
      desc: 'Restores 42% Max HP to all allies.', anim: 'glow' },
    // ===== Enemy skills =====
    wildSwing:    { name: 'Wild Swing',    type: 'attack', target: 'enemy', mul: 1.3, cd: 0,
      desc: 'A reckless swing. 1.3x ATK.', anim: 'lunge' },
    waterCurse:   { name: 'Water Curse',   type: 'attack', target: 'enemy', mul: 1.35, cd: 0,
      desc: 'A hex of cold water. 1.35x ATK.', anim: 'lunge' },
    cleave:       { name: 'Cleave',        type: 'aoe',    target: 'enemies', mul: 0.9, cd: 3,
      desc: 'Cleaves all enemies. 0.9x ATK.', anim: 'lunge' },
    roar:         { name: 'Roar',          type: 'buff',   target: 'allies', cd: 4,
      desc: "Boosts allies' ATK by 25% for 2 turns.", anim: 'glow',
      onCast: { kind: 'buff', stat: 'atk', amount: 0.25, turns: 2, label: 'ATK+' } },
    bite:         { name: 'Bite',          type: 'attack', target: 'enemy', mul: 1.25, cd: 0,
      desc: 'A vicious bite. 1.25x ATK.', anim: 'lunge' },
    pounce:       { name: 'Pounce',        type: 'attack', target: 'enemy', mul: 1.7, cd: 3,
      desc: 'A leaping strike. 1.7x ATK.', anim: 'lunge' },
    howl:         { name: 'Howl',          type: 'buff',   target: 'allies', cd: 4,
      desc: "Allies' SPD +20% for 2 turns.", anim: 'glow',
      onCast: { kind: 'buff', stat: 'spd', amount: 0.20, turns: 2, label: 'SPD+' } },
    boneJab:      { name: 'Bone Jab',      type: 'attack', target: 'enemy', mul: 1.2, cd: 0,
      desc: 'A jab with a bony fist. 1.2x ATK.', anim: 'lunge' },
    decay:        { name: 'Decay',         type: 'attack', target: 'enemy', mul: 1.4, cd: 2,
      desc: '1.4x ATK. 50% chance to reduce DEF by 20% for 2 turns.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'def', amount: -0.20, turns: 2, chance: 0.50, label: 'DEF-' } },
    deathPulse:   { name: 'Death Pulse',   type: 'aoe',    target: 'enemies', mul: 1.0, cd: 4,
      desc: 'Pulse of necrotic energy. 1.0x ATK to all.', anim: 'lunge' },
    crystalStrike:{ name: 'Crystal Strike', type: 'attack', target: 'enemy', mul: 1.15, cd: 0,
      desc: 'A blunt crystalline punch. 1.15x ATK light damage.', anim: 'lunge' },
    prismBarrier: { name: 'Prism Barrier',  type: 'buff',   target: 'self', cd: 4,
      desc: 'Self shield = 35% Max HP for 2 turns. DEF +30% for 2 turns.', anim: 'glow',
      onCast: { kind: 'shield', pct: 0.35, turns: 2, label: 'SHIELD' },
      onSelf: { kind: 'buff', stat: 'def', amount: 0.30, turns: 2, label: 'DEF+' } },
    wraithTouch:  { name: 'Wraith Touch',   type: 'attack', target: 'enemy', mul: 1.8, cd: 0,
      desc: 'A spectral strike. 1.8x ATK. 35% chance to stun for 1 turn.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'stun', chance: 0.35, turns: 1, label: 'STUN' } },
    veilStep:     { name: 'Veil Step',      type: 'buff',   target: 'self', cd: 4,
      desc: 'Phase through the veil. ATK +30% and SPD +30% for 2 turns.', anim: 'glow',
      onCast: { kind: 'buff', stat: 'atk', amount: 0.30, turns: 2, label: 'ATK+' },
      onSelf: { kind: 'buff', stat: 'spd', amount: 0.30, turns: 2, label: 'SPD+' } },
    soulReap:     { name: 'Soul Reap',      type: 'aoe',    target: 'enemies', mul: 1.2, cd: 3,
      desc: '1.2x ATK to all. 50% chance to reduce DEF by 25% for 2 turns.', anim: 'lunge',
      onHit: { kind: 'debuff', stat: 'def', amount: -0.25, chance: 0.50, turns: 2, label: 'DEF-' } },
    undeathRite:  { name: 'Undeath Rite',   type: 'buff',   target: 'allies', cd: 5,
      desc: "Channels undeath. All allies' ATK +35% for 2 turns.", anim: 'glow',
      onCast: { kind: 'buff', stat: 'atk', amount: 0.35, turns: 2, label: 'ATK+' } },
    // ---- Luminos (Light Ranger) ----
    radiantArrow: { name: 'Radiant Arrow',  type: 'attack',  mul: 1.3, cd: 0, target: 'enemy',
      desc: '1.3x ATK light shot. 40% chance to reduce ATK by 20% for 2 turns.',
      onHit: { kind: 'debuff', stat: 'atk', amount: -0.20, turns: 2, label: 'ATK-', chance: 0.40 } },
    holyVolley:   { name: 'Holy Volley',    type: 'multihit', mul: 0.65, hits: 3, cd: 3, target: 'enemy',
      desc: '0.65x ATK × 3 hits with +10% crit rate.',
      critBonus: 0.10 },
    // ---- Voidweaver (Dark Mage) ----
    voidPulse:    { name: 'Void Pulse',     type: 'attack',  mul: 1.1, cd: 0, target: 'enemy',
      desc: '1.1x ATK. 50% chance to reduce SPD by 25% for 2 turns.',
      onHit: { kind: 'debuff', stat: 'spd', amount: -0.25, turns: 2, label: 'SPD-', chance: 0.50 } },
    entropyWave:  { name: 'Entropy Wave',   type: 'aoe',     mul: 0.95, cd: 4, target: 'enemies',
      desc: '0.95x ATK to all enemies. 65% chance to reduce ATK by 20% for 2 turns.',
      onHit: { kind: 'debuff', stat: 'atk', amount: -0.20, turns: 2, label: 'ATK-', chance: 0.65 } },
    // ---- Cinder Sage (Fire Healer) ----
    emberBlast:   { name: 'Ember Blast',    type: 'attack',  mul: 1.2, cd: 0, target: 'enemy',
      desc: 'A scorching burst of fire energy. 1.2x ATK fire damage.' },
    kindlingMend: { name: 'Kindling Mend',  type: 'heal',    target: 'allies', healPct: 0.30, cd: 3,
      desc: 'Ignites the healing flame in all allies, restoring 30% of their Max HP.' },
  };

  const HEROES = [
    // ===== 3* =====
    { id: 'ember_knight', name: 'Ember Knight', element: 'fire', role: 'Warrior', stars: 3,
      art: { kind: 'warrior', accent: '#ffe2b3',
        hair: 'short_male', hairColor: '#3a1a0a', beard: 'stubble', helm: 'horned_knight',
        weapon: 'flame_sword', brows: 'fierce', mouth: 'smile' },
      base: { hp: 1900, atk: 250, def: 130, spd: 95, critRate: 0.15, critDmg: 0.55 },
      skills: ['burningSlash', 'cinderWave'] },
    { id: 'tide_caller', name: 'Tide Caller', element: 'water', role: 'Mage', stars: 3,
      art: { kind: 'mage', accent: '#cfeaff',
        hair: 'long_flow', hairColor: '#2a5878', helm: 'wizard_hat',
        weapon: 'trident', brows: 'arched', mouth: 'smirk' },
      base: { hp: 1500, atk: 320, def: 80, spd: 100, critRate: 0.12, critDmg: 0.5 },
      skills: ['waterBolt', 'tsunami'] },
    { id: 'gale_archer', name: 'Gale Archer', element: 'wind', role: 'Ranger', stars: 3,
      art: { kind: 'ranger', accent: '#d8ffd2',
        hair: 'long_bangs', hairColor: '#caa75e', helm: 'hood_simple',
        weapon: 'longbow', quiver: true, ears: 'pointed', brows: 'normal', mouth: 'smirk' },
      base: { hp: 1450, atk: 280, def: 90, spd: 130, critRate: 0.20, critDmg: 0.55 },
      skills: ['quickShot', 'hurricaneVolley'] },
    { id: 'dawn_cleric', name: 'Dawn Cleric', element: 'light', role: 'Healer', stars: 3,
      art: { kind: 'healer', accent: '#fff4c8',
        hair: 'long_flow', hairColor: '#f0d68c', helm: 'cleric_veil',
        weapon: 'mace_holy', eyes: 'closed', brows: 'arched', mouth: 'smile' },
      base: { hp: 1700, atk: 200, def: 110, spd: 110, critRate: 0.10, critDmg: 0.5 },
      skills: ['smite', 'sanctifiedLight'] },
    { id: 'shade_stalker', name: 'Shade Stalker', element: 'dark', role: 'Assassin', stars: 3,
      art: { kind: 'assassin', accent: '#e9d4ff',
        hair: 'spiky', hairColor: '#1a0e2a', helm: 'hood_pointy',
        weapon: 'twin_daggers', eyes: 'glow', brows: 'fierce' },
      base: { hp: 1300, atk: 380, def: 70, spd: 140, critRate: 0.30, critDmg: 0.70 },
      skills: ['shadowStrike', 'veilOfNight'] },
    { id: 'stone_guardian', name: 'Stone Guardian', element: 'fire', role: 'Tank', stars: 3,
      art: { kind: 'tank', accent: '#ffd9b3',
        hair: 'short_male', hairColor: '#4a3a2a', beard: 'full', beardColor: '#3a2a1a',
        helm: 'open_helm', weapon: 'tower_shield', brows: 'fierce', mouth: 'smile' },
      base: { hp: 2500, atk: 180, def: 220, spd: 75, critRate: 0.05, critDmg: 0.50 },
      skills: ['crushingBlow', 'aegis'] },
    { id: 'aqua_warden', name: 'Aqua Warden', element: 'water', role: 'Tank', stars: 3,
      art: { kind: 'tank', accent: '#bfeaff',
        hair: 'short_male', hairColor: '#3a5a78', beard: 'goatee',
        helm: 'open_helm', weapon: 'tower_shield', brows: 'normal', mouth: 'smile' },
      base: { hp: 2400, atk: 170, def: 230, spd: 80, critRate: 0.05, critDmg: 0.50 },
      skills: ['frostBash', 'bulwark'] },
    { id: 'zephyr_duelist', name: 'Zephyr Duelist', element: 'wind', role: 'Warrior', stars: 3,
      art: { kind: 'warrior', accent: '#caffd0',
        hair: 'side_swept', hairColor: '#88c8a0', helm: 'circlet',
        weapon: 'rapier', ears: 'pointed', brows: 'normal', mouth: 'smirk' },
      base: { hp: 1700, atk: 270, def: 110, spd: 125, critRate: 0.20, critDmg: 0.60 },
      skills: ['swiftStrike', 'riposte'] },
    // ===== 4* =====
    { id: 'inferno_witch', name: 'Inferno Witch', element: 'fire', role: 'Mage', stars: 4,
      art: { kind: 'mage', accent: '#ffb499',
        hair: 'long_flow', hairColor: '#aa2a18', helm: 'witch_hat',
        weapon: 'staff_orb', brows: 'arched', mouth: 'smirk' },
      base: { hp: 2100, atk: 448, def: 112, spd: 110, critRate: 0.18, critDmg: 0.60 },
      skills: ['flameWhip', 'infernoCage'] },
    { id: 'tidal_knight', name: 'Tidal Knight', element: 'water', role: 'Warrior', stars: 4,
      art: { kind: 'warrior', accent: '#9fdcff',
        hair: 'short_male', hairColor: '#1a3a5a', helm: 'horned_knight',
        weapon: 'lance', brows: 'fierce', mouth: 'smile' },
      base: { hp: 2660, atk: 350, def: 182, spd: 100, critRate: 0.18, critDmg: 0.55 },
      skills: ['tideStrike', 'whirlpoolGuard'] },
    { id: 'storm_lancer', name: 'Storm Lancer', element: 'wind', role: 'Warrior', stars: 4,
      art: { kind: 'warrior', accent: '#b8ffaf',
        hair: 'bowl', hairColor: '#caa75e', helm: 'circlet',
        weapon: 'lance', brows: 'fierce', mouth: 'smirk' },
      base: { hp: 2100, atk: 392, def: 126, spd: 140, critRate: 0.30, critDmg: 0.65 },
      skills: ['thunderLance', 'galeRush'] },
    { id: 'radiant_oracle', name: 'Radiant Oracle', element: 'light', role: 'Healer', stars: 4,
      art: { kind: 'healer', accent: '#ffe89a',
        hair: 'long_flow', hairColor: '#fff2b6', helm: 'cleric_veil',
        weapon: 'staff_orb', eyes: 'closed', brows: 'arched', mouth: 'smile' },
      base: { hp: 2380, atk: 280, def: 154, spd: 115, critRate: 0.12, critDmg: 0.55 },
      skills: ['judgmentLight', 'dawnsBlessing'] },
    { id: 'twilight_reaver', name: 'Twilight Reaver', element: 'dark', role: 'Assassin', stars: 4,
      art: { kind: 'assassin', accent: '#d2a8ff',
        hair: 'spiky', hairColor: '#2a0e3a', helm: 'hood_pointy', horns: 'devil', hornColor: '#1a0e2a',
        weapon: 'twin_daggers', eyes: 'glow', brows: 'fierce' },
      base: { hp: 1820, atk: 532, def: 98, spd: 150, critRate: 0.32, critDmg: 0.75 },
      skills: ['eclipseStrike', 'voidStep'] },
    { id: 'bone_warden', name: 'Bone Warden', element: 'dark', role: 'Tank', stars: 4,
      art: { kind: 'tank', accent: '#cfb4ff',
        hair: '', helm: 'open_helm', horns: 'curled', hornColor: '#e6e8ec',
        weapon: 'tower_shield', brows: 'fierce', mouth: 'open' },
      base: { hp: 3360, atk: 252, def: 308, spd: 78, critRate: 0.08, critDmg: 0.55 },
      skills: ['bonecrush', 'reaperGuard'] },
    // ===== 5* =====
    { id: 'pyre_sovereign', name: 'Pyre Sovereign', element: 'fire', role: 'Champion', stars: 5,
      art: { kind: 'warrior', accent: '#ffc88a',
        hair: 'long_flow', hairColor: '#aa4018', beard: 'full', beardColor: '#3a1a0a',
        helm: 'crown', cape: true, weapon: 'flame_sword', brows: 'fierce', mouth: 'smile' },
      base: { hp: 3420, atk: 450, def: 234, spd: 115, critRate: 0.25, critDmg: 0.75 },
      skills: ['phoenixBlade', 'emberStorm'] },
    { id: 'aurora_seraph', name: 'Aurora Seraph', element: 'light', role: 'Healer', stars: 5,
      art: { kind: 'healer', accent: '#fff2c2',
        hair: 'long_flow', hairColor: '#fff5d0', helm: 'circlet', cape: true,
        weapon: 'mace_holy', eyes: 'closed', brows: 'arched', mouth: 'smile' },
      base: { hp: 3060, atk: 360, def: 198, spd: 125, critRate: 0.15, critDmg: 0.60 },
      skills: ['starfire', 'celestialBloom'] },
    { id: 'storm_herald', name: 'Storm Herald', element: 'wind', role: 'Champion', stars: 5,
      art: { kind: 'warrior', accent: '#c8ffca',
        hair: 'long_flow', hairColor: '#8fca90', helm: 'circlet', cape: true,
        weapon: 'lance', brows: 'fierce', mouth: 'smile' },
      base: { hp: 2880, atk: 540, def: 180, spd: 145, critRate: 0.28, critDmg: 0.80 },
      skills: ['galeStrike', 'cycloneBreak'] },
    { id: 'void_sovereign', name: 'Void Sovereign', element: 'dark', role: 'Champion', stars: 5,
      art: { kind: 'assassin', accent: '#c8a8ff',
        hair: 'spiky', hairColor: '#1a0a2e', helm: 'hood_pointy', horns: 'curled', hornColor: '#4a2a8a',
        weapon: 'twin_daggers', eyes: 'glow', brows: 'fierce', cape: true },
      base: { hp: 2700, atk: 580, def: 160, spd: 135, critRate: 0.35, critDmg: 0.85 },
      skills: ['voidSlash', 'abyssalEdge'] },
    { id: 'tidal_sage', name: 'Tidal Sage', element: 'water', role: 'Sage', stars: 5,
      art: { kind: 'healer', accent: '#aadeff',
        hair: 'long_flow', hairColor: '#4a8aaa', helm: 'cleric_veil', cape: true,
        weapon: 'staff_orb', eyes: 'closed', brows: 'arched', mouth: 'smile' },
      base: { hp: 3240, atk: 320, def: 216, spd: 115, critRate: 0.12, critDmg: 0.55 },
      skills: ['tidalSurge', 'divineRestoration'] },
    // ===== Additional 4* — Light Ranger & Dark Mage =====
    { id: 'luminos',    name: 'Luminos',    element: 'light', role: 'Ranger',  stars: 4,
      art: { kind: 'ranger', accent: '#ffd86a',
        hair: 'long_flow', hairColor: '#f0d870', helm: 'circlet',
        weapon: 'longbow', quiver: true, ears: 'pointed', brows: 'arched', mouth: 'smile' },
      base: { hp: 2600, atk: 290, def: 155, spd: 110, critRate: 0.18, critDmg: 0.50 },
      skills: ['radiantArrow', 'holyVolley'] },
    { id: 'voidweaver', name: 'Voidweaver', element: 'dark',  role: 'Mage',    stars: 4,
      art: { kind: 'mage', accent: '#c084ff',
        hair: 'long_flow', hairColor: '#0a0618', helm: 'hood_simple',
        weapon: 'staff_orb', brows: 'fierce', mouth: 'smirk' },
      base: { hp: 2200, atk: 320, def: 130, spd: 100, critRate: 0.15, critDmg: 0.55 },
      skills: ['voidPulse', 'entropyWave'] },
    // ===== Additional 3* — Fire Healer (fills a key role gap) =====
    { id: 'cinder_sage', name: 'Cinder Sage', element: 'fire', role: 'Healer', stars: 3,
      art: { kind: 'healer', accent: '#ffb499',
        hair: 'long_flow', hairColor: '#cc4c10', helm: 'cleric_veil',
        weapon: 'mace_holy', eyes: 'closed', brows: 'arched', mouth: 'smile' },
      base: { hp: 1750, atk: 195, def: 105, spd: 105, critRate: 0.10, critDmg: 0.50 },
      skills: ['emberBlast', 'kindlingMend'] },
  ];

  const ENEMIES = [
    { id: 'goblin_brawler', name: 'Goblin Brawler', element: 'wind', role: 'Brute', stars: 2,
      art: { kind: 'goblin', accent: '#b6f0a8' },
      base: { hp: 900, atk: 150, def: 60, spd: 90, critRate: 0.10, critDmg: 0.5 },
      skills: ['wildSwing'] },
    { id: 'goblin_shaman', name: 'Goblin Shaman', element: 'water', role: 'Caster', stars: 2,
      art: { kind: 'goblin_shaman', accent: '#bee2ff' },
      base: { hp: 780, atk: 200, def: 50, spd: 95, critRate: 0.10, critDmg: 0.5 },
      skills: ['waterCurse'] },
    { id: 'goblin_chief', name: 'Goblin Chief', element: 'fire', role: 'Champion', stars: 3,
      art: { kind: 'goblin_chief', accent: '#ffd1b3' },
      base: { hp: 1400, atk: 220, def: 100, spd: 85, critRate: 0.15, critDmg: 0.55 },
      skills: ['cleave', 'roar'] },
    { id: 'forest_wolf', name: 'Forest Wolf', element: 'wind', role: 'Brute', stars: 2,
      art: { kind: 'wolf', accent: '#b8c8a0' },
      base: { hp: 850, atk: 180, def: 55, spd: 120, critRate: 0.15, critDmg: 0.55 },
      skills: ['bite'] },
    { id: 'alpha_wolf', name: 'Alpha Wolf', element: 'wind', role: 'Champion', stars: 3,
      art: { kind: 'wolf_chief', accent: '#a8b88c' },
      base: { hp: 1500, atk: 240, def: 100, spd: 115, critRate: 0.20, critDmg: 0.60 },
      skills: ['pounce', 'howl'] },
    { id: 'skeleton_marauder', name: 'Skeleton Marauder', element: 'dark', role: 'Brute', stars: 2,
      art: { kind: 'skeleton', accent: '#d4d8e8' },
      base: { hp: 950, atk: 170, def: 65, spd: 85, critRate: 0.10, critDmg: 0.55 },
      skills: ['boneJab'] },
    { id: 'lich_acolyte', name: 'Lich Acolyte', element: 'dark', role: 'Caster', stars: 3,
      art: { kind: 'lich', accent: '#c8a8ff' },
      base: { hp: 1100, atk: 280, def: 70, spd: 100, critRate: 0.18, critDmg: 0.60 },
      skills: ['decay', 'deathPulse'] },
    { id: 'crystal_golem', name: 'Crystal Golem', element: 'light', role: 'Behemoth', stars: 4,
      art: { kind: 'tank', accent: '#fff8d0' },
      base: { hp: 2200, atk: 200, def: 320, spd: 60, critRate: 0.05, critDmg: 0.50 },
      skills: ['crystalStrike', 'prismBarrier'] },
    { id: 'aether_wraith', name: 'Aether Wraith', element: 'dark', role: 'Specter', stars: 4,
      art: { kind: 'wraith', accent: '#c8a8ff' },
      base: { hp: 1400, atk: 350, def: 80, spd: 155, critRate: 0.25, critDmg: 0.65 },
      skills: ['wraithTouch', 'veilStep'] },
    { id: 'elder_lich', name: 'Elder Lich', element: 'dark', role: 'Overlord', stars: 5,
      art: { kind: 'lich_lord', accent: '#d0b0ff' },
      base: { hp: 3000, atk: 380, def: 200, spd: 95, critRate: 0.20, critDmg: 0.65 },
      skills: ['soulReap', 'undeathRite'] },
  ];

  const STAGES = [
    { id: 'goblin_camp_1', name: 'Goblin Camp · I', tier: 1,
      desc: 'A noisy camp on the outskirts of the Aether.',
      enemyIds: ['goblin_brawler', 'goblin_shaman', 'goblin_chief'],
      enemyMul: 1.0, rewardMul: 1.0 },
    { id: 'forest_path', name: 'Forest Path', tier: 2,
      desc: 'Wolves prowl the moonlit path. Their alpha leads the pack.',
      enemyIds: ['forest_wolf', 'forest_wolf', 'alpha_wolf'],
      enemyMul: 1.25, rewardMul: 1.5 },
    { id: 'goblin_camp_2', name: 'Goblin Camp · II', tier: 2,
      desc: 'The goblins regroup with a shaman calling the shots. Expect curses.',
      enemyIds: ['goblin_shaman', 'goblin_chief', 'goblin_shaman'],
      enemyMul: 1.15, rewardMul: 1.6 },
    { id: 'cursed_ruins', name: 'Cursed Ruins', tier: 3,
      desc: 'Skeletons rise from cracked earth, led by a lich acolyte.',
      enemyIds: ['skeleton_marauder', 'skeleton_marauder', 'lich_acolyte'],
      enemyMul: 1.5, rewardMul: 2.0 },
    { id: 'shadow_bog', name: 'Shadow Bog', tier: 3,
      desc: 'The bog reeks of death. Wolves and skeletons hunt together in the dark.',
      enemyIds: ['forest_wolf', 'skeleton_marauder', 'alpha_wolf'],
      enemyMul: 1.4, rewardMul: 2.2 },
    { id: 'warchief_hall', name: "Warchief's Hall", tier: 4,
      desc: 'Three warchiefs guard the heart of the goblin lair.',
      enemyIds: ['goblin_chief', 'goblin_chief', 'goblin_chief'],
      enemyMul: 1.8, rewardMul: 2.4 },
    { id: 'bone_crypt', name: 'Bone Crypt', tier: 4,
      desc: 'Deep beneath the ruins, the lich acolyte commands an undead assault.',
      enemyIds: ['skeleton_marauder', 'lich_acolyte', 'skeleton_marauder'],
      enemyMul: 1.65, rewardMul: 2.6 },
    { id: 'crystal_vaults', name: 'Crystal Vaults', tier: 5,
      desc: 'Ancient constructs guard forgotten treasure.',
      enemyIds: ['crystal_golem', 'aether_wraith', 'crystal_golem'],
      enemyMul: 2.2, rewardMul: 3.0 },
    { id: 'aether_gate', name: 'The Aether Gate', tier: 6,
      desc: 'The Elder Lich reigns at the threshold. Undeath and shadow converge here.',
      enemyIds: ['aether_wraith', 'elder_lich', 'aether_wraith'],
      enemyMul: 2.8, rewardMul: 4.5 },
  ];

  // ===== RUNE SYSTEM =====
  const RUNE_TYPES = {
    fury:   { id: 'fury',   name: 'Fury',    icon: 'ATK', color: '#ff6a4d',
              set2: { stat: 'atk', pct: 0.08 }, set4: { stat: 'atk', pct: 0.35 } },
    guard:  { id: 'guard',  name: 'Guard',   icon: 'DEF', color: '#5ab9ff',
              set2: { stat: 'def', pct: 0.10 }, set4: { stat: 'def', pct: 0.50 } },
    spirit: { id: 'spirit', name: 'Spirit',  icon: 'HP',  color: '#6df09a',
              set2: { stat: 'hp',  pct: 0.08 }, set4: { stat: 'hp',  pct: 0.25 } },
    swift:  { id: 'swift',  name: 'Swift',   icon: 'SPD', color: '#ffd86a',
              set2: { stat: 'spd', pct: 0.06 }, set4: { stat: 'spd', pct: 0.25 } },
    rage:   { id: 'rage',   name: 'Rage',    icon: 'CR',  color: '#ffb454',
              set2: { stat: 'critRate', pct: 0.07 }, set4: { stat: 'critDmg', pct: 0.40 } },
    blade:  { id: 'blade',  name: 'Blade',   icon: 'CD',  color: '#c084ff',
              set2: { stat: 'critDmg', pct: 0.12 } },
  };

  const RUNE_SLOT_STATS = {
    1: ['atk'],
    2: ['hp', 'atk', 'def', 'spd'],
    3: ['def'],
    4: ['atk', 'hp', 'spd', 'critRate', 'critDmg'],
    5: ['atk', 'hp', 'def'],
    6: ['hp', 'atk', 'def', 'spd'],
  };

  const RUNE_SUB_STATS = ['atk', 'def', 'hp', 'spd', 'critRate', 'critDmg'];

  const RUNE_STAT_LABEL = {
    atk: 'ATK', def: 'DEF', hp: 'HP', spd: 'SPD', critRate: 'Crit Rate', critDmg: 'Crit DMG',
  };

  function heroById(id)    { return HEROES.find(h => h.id === id) || null; }
  function enemyById(id)   { return ENEMIES.find(e => e.id === id) || null; }
  function heroesByStars(s){ return HEROES.filter(h => h.stars === s); }
  function stageById(id)   { return STAGES.find(s => s.id === id) || null; }
  function stagesByTier(t) { return STAGES.filter(s => s.tier === t); }

  window.GAME_DATA = {
    ELEMENTS, SKILLS, HEROES, ENEMIES, STAGES, TIER_SCALE,
    RUNE_TYPES, RUNE_SLOT_STATS, RUNE_SUB_STATS, RUNE_STAT_LABEL,
    elementMod, heroById, enemyById, heroesByStars, stageById, stagesByTier,
  };
})();
