import { JSDOM } from 'jsdom';
import fs from 'node:fs';
import path from 'node:path';
const ROOT = path.resolve('..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const stripped = html.replace(/<script\s+src=[^>]*><\/script>/g, '');
const dom = new JSDOM(stripped, { url: 'http://localhost/', runScripts:'dangerously', pretendToBeVisual:true });
const w = dom.window;
w.confirm = () => true;
function inj(f){ const s=w.document.createElement('script'); s.textContent=fs.readFileSync(path.join(ROOT,f),'utf8'); w.document.body.appendChild(s); }
['data.js','art.js','save.js','summon.js','combat.js','ui.js','game.js'].forEach(inj);
await new Promise(r=>setTimeout(r,80));
const G = w.__GAME__, S = w.GAME_SAVE;
S.clear();
G.state.player = S.loadOrInit();
G.persistNow();
console.log('Before setSelectedHeroIds');
G.setSelectedHeroIds(G.state.player.ownedInstances.slice(0, 3).map(i => i.id));
console.log('Before confirmTeam');
G.confirmTeam();
console.log('After confirmTeam, battle:', !!G.state.battle, 'lastStage:', !!G.state.lastStage);
G.state.battle.enemy.forEach(e => { e.hp = 0; });
G.state.battle.result = 'victory';
console.log('Before grantVictoryRewards');
G.grantVictoryRewards();
console.log('Rewards:', JSON.stringify(G.state.battle.rewards));
console.log('Before rebattle');
G.rebattle();
console.log('After rebattle, battle exists:', !!G.state.battle, 'ally count:', G.state.battle?.ally?.length);
console.log('DONE');
process.exit(0);
